name: Gatsby Publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: rjriel/gatsby-gh-pages-action@9d475bd
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
